### ISSUE TITLE
OnlyKey dongle support OTP & U2F

### ISSUE THREAD

**Issue by toastal** [Nitrokey/dongleauth#103]
https://crp.to/p/

**Comment by onlykey** [comment]
@techge Thanks for adding OnlyKey to the list!

I noticed that the placeholder logo is missing so the page currently displays like this -
![image](https://user-images.githubusercontent.com/18121756/36109081-5cecc6d2-0fec-11e8-9e2d-8d670bc575b8.png)

Here is the logo 32x32 logo - https://github.com/trustcrypto/OnlyKey-BrowserCrypt/raw/master/images/icon32.png

Also, only OTP box is checked, OnlyKey supports OTP, U2F, and Yubikey OTP. 

Thanks for building this great 2FA knowledge base!

**Comment by alex-nitrokey** [comment]
Hi,

thanks for the icon! I couldn't find it easily first. The u2f was just a typo in the yml file :)
Both should be fixed now.
