### ISSUE TITLE
Clarify intent of twofactorauth fork, differences and goal in documentation/README

### ISSUE THREAD

**Issue by gene1wood** [Nitrokey/dongleauth#104]
`dongleauth.info` contains different information from [twofactorauth](https://github.com/2factorauth/twofactorauth) (adds U2F support, removes SMS/phonecall/email/hardware/software). 

Would it be possible to add to the README or the site itself, the reason for the fork from `twofactorauth` (likely to add information about U2F?) and what the intent of the site is? I ask because I'm unsure why dongleauth removes the information about support for SMS/email/etc that's present on `twofactorauth`. I'm also curious about the approach to merging upstream changes from `twofactorauth`.

Generally, just some information about the fork would be a great addition.

**Comment by techge** [comment]
We will do some major changes soon. Try to keep this in mind when doing this, thx.

**Comment by gene1wood** [comment]
Thanks!

**Comment by iocoop** [comment]
This text was added to the README in e508580113d3bdf7dc5e4b0880f7bcea168b19cb

**Comment by gene1wood** [comment]
This text was added to the README in e508580
