### ISSUE TITLE
Clarify whether services support U2F in general or only for paid accounts

### ISSUE THREAD

**Issue by mbirth** [Nitrokey/dongleauth#110]
Some services (e.g. Bitwarden) only support U2F tokens for paying customers and not for the free accounts. This should probably be mentioned/made visible in some way.

**Comment by alex-nitrokey** [comment]
This can be noted by a exception note (see CONTRIBUTING.md) and the specific case was solved by https://github.com/Nitrokey/dongleauth/commit/cf8cb86035166ade5ac9d71297f40115aab490f8
