### ISSUE TITLE
U2F now works in Firefox if you enable security.webauth.u2f

### ISSUE THREAD

**Issue by mbirth** [Nitrokey/dongleauth#111]
Firefox now includes support for U2F tokens. You just have to enable the setting `security.webauth.u2f` in `about:config`. Tested with Firefox 57 "Quantum".

**Comment by Gunni** [comment]
Downside of course being that most vendors are doing user agent sniffing instead of feature detection or just always showing it, allowing failures to happen...

Gitlab and Github work for example, facebook/google and more do not.

**Comment by Vednier** [comment]
U2F doesnt supported in Firefox 57 officially (and so far its dont looks like they enables it officially in 58 either). Also, their implementation seems to be not yet polished enough (a lot of bugs found) and facets is not fully supported (problematic for complex cases like Facebook).

**Comment by techge** [comment]
I would rather not include it on this page as long as it is not ready for average users. Changing settings in about:config is the exact thing which is not compatible with "average" user, I am afraid.
We're happy if you get us updated on this!

**Comment by Vednier** [comment]
According to https://groups.google.com/forum/#!msg/mozilla.dev.platform/tsevyqfBHLE/lccldWNNBwAJ Mozilla plans to officially support Webauth (including U2F) in Firefox 60
And in https://bugzilla.mozilla.org/show_bug.cgi?id=1428918 its already enabled for Firefox Nightly (previous it was disabled even here).

**Comment by Vednier** [comment]
Clarification: Webauth is indeed planned for Firefox 60 (and almost ready) with U2F hardware used on client side, BUT FIDO U2F APis as is not going to be supported officially (and will not be enabled by default) in favor to WebAuth standard. Google Chrome (Chromium) is going to support WebAuth as well, its in beta now. Sites is expected to move from pure U2F JS API to WebAuth.

**Comment by Vednier** [comment]
Firefox 60 was released at May 9 with WebAuthn support enabled which supersedes FIDO U2F.

**Comment by beerisgood** [comment]
Now only the u2f Nitrokey is missing. Any plans when release is?

**Comment by alex-nitrokey** [comment]
As far as I can see, this issue does not propose any specific change, does it? But it kind of results in #129, doesn't it?

**Comment by alex-nitrokey** [comment]
> Now only the u2f Nitrokey is missing. Any plans when release is?

I personally don't know, sorry.

**Comment by Vednier** [comment]
Maybe its time to close this issue? Both Firefox and Chrome now released with WebAuthn+U2F support.

**Comment by alex-nitrokey** [comment]
Well, I would close it without changing anything, right? As far as I can see this issue is not about proposing any change or adding anything.
