### ISSUE TITLE
GUI: Full view/Show all/Spreadsheet mode

### ISSUE THREAD

**Issue by brenthuisman** [Nitrokey/dongleauth#114]
A while ago the website GUI was altered to show only one category at once. I liked the old view, all categories at once with an index on top better. Would it be possible to get a show all button or a single-table mode or something?

**Comment by techge** [comment]
I am not sure, what you mean... Can you explain further? Basically we try to be mostly compatible to [2factorauth/twofactorauth](https://github.com/2factorauth/twofactorauth) which we definitely lost in the last months. We'll fix this soon.

This is to make the amount of work needed to update the site as small as possible. If this is a small and simple change, we may do it. But as I said, until now I don't understand :-)

**Comment by brenthuisman** [comment]
The request is to be able to view all services at once, without bothering to unfold per category (or know in which category a service is categorized). I think the amount of work needed for this is small, just set `display:block` for all divs (through a toggle button).

**Comment by alex-nitrokey** [comment]
I tried to make this repo more similar to upstream to ease updates between both. I think this request would do the opposite. But if you propose a clean and quick change as PR, I will gladly have look.

Sorry.
