### ISSUE TITLE
Supported by software: phpMyAdmin and Joomla

### ISSUE THREAD

**Issue by Vednier** [Nitrokey/dongleauth#115]
It seems starting from PMA 4.8 U2F will be supported almost "from the box" - https://docs.phpmyadmin.net/en/latest/two_factor.html

Also, there is LoginGuard plugin for Joomla which implements U2F (and other variants too including Yubikey) - https://www.akeebabackup.com/products/loginguard.html

**Comment by techge** [comment]
I am not sure if this can be included within the logic of the site. Where would you put this in? In general this is not a service but a option to include for operators of PMA or Joomla sites...

**Comment by Vednier** [comment]
How Linux PAM can fit in this logic then? Both PMA and Joomla at least related to web while Linux PAM is local auth service.

**Comment by alex-nitrokey** [comment]
Good point. To be honest, I think this fits even less :thinking: 
I plan to restructure this project a bit within the next weeks (as soon as I find the time). I will rethink this then thus keeping the issue open.

**Comment by alex-nitrokey** [comment]
Okay, as twofactorauth only adds services, not software I close this.

Generally we shouldn't include sites that twofactorauth doesn't. Thus, every PR with a new site must fit in their definition (except: the hardware part :wink:).

I did remove mentioned stuff in d66a456 as well.

**Comment by alex-nitrokey** [comment]
Still feeling like this could get out of hand, but: I created a new section "[software](https://www.dongleauth.info/#software)" for self-hosted services that support dongles as a second factor in b906125. 

Anyone in the mood to include the above mentioned software is welcome to create a PR now :smile:
