### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by rugk** [Nitrokey/dongleauth#118]
This site needs HTTPS. https://doesmysiteneedhttps.com/

**Comment by beerisgood** [comment]
Site have HTTPS, but a invalid cert
https://www.ssllabs.com/ssltest/analyze.html?d=www.dongleauth.info

**Comment by rugk** [comment]
Okay, this basically means it has no HTTPS, HTTPS with invalid cert is not HTTPS.

And I know, GitHub hosting. So you may either use GitHub.io subdomain or use a CDN with HTTPS support or something like that.

**Comment by techge** [comment]
We are quite aware of it and plan to implement SSL, beforehand we have to update the site's content and improve the workflow of merge PR etc. 
I'll try to do it soon and will look how we get proper SSL here...

**Comment by techge** [comment]
#80

**Comment by techge** [comment]
This is requested here #80 as well. Will close it.
