### ISSUE TITLE
Search misses some entries

### ISSUE THREAD

**Issue by bpburns** [Nitrokey/dongleauth#130]
Search misses some entries in the list. E.g., when typing "Facebook" into the search box, the website says "No results found," but an entry for Facebook is found in the "Social" section. See screenshots.
![1](https://user-images.githubusercontent.com/3639671/40245802-74c4f94e-5a7b-11e8-9926-120c3e86e173.PNG)
![2](https://user-images.githubusercontent.com/3639671/40245804-74e168b8-5a7b-11e8-817a-c2fe1f503fab.PNG)

**Comment by alex-nitrokey** [comment]
Fixed via 70193f4 thx
