### ISSUE TITLE
Filter services by dongle support

### ISSUE THREAD

**Issue by coder543** [Nitrokey/dongleauth#131]
It would be nice to have the option of filtering to only see websites that _do_ support a particular dongle auth method (U2F or OTP), rather than having to see lots of websites that don't support e.g. U2F when all I care about is U2F support. Just an idea!

**Comment by alex-nitrokey** [comment]
This duplicate to #11 

I'd like to stay close to upstream (twofactorauth.org). While I see the point in having this option, I don't have the time to support such function. If you propose a PR I gladly look at it and merge it eventually.
