### ISSUE TITLE
Add Nextcloud

### ISSUE THREAD

**Issue by sbrl** [Nitrokey/dongleauth#135]
It's a popular self-hosted alternative to Google Drive, and it supports 2-factor authentication (both vua U2F and OTP) via a pair of extensions.

Website: https://nextcloud.com/

**Comment by alex-nitrokey** [comment]
Won't happen because twofactorauth.org don't want these ones included. See [here](https://github.com/2factorauth/twofactorauth/issues/3030). To keep maintenance low, we stick to their rules.

**Comment by sbrl** [comment]
@alex-nitrokey .....I don't understand the logic here.

Anyway, I would seriously recommend updating the contributing guidelines so that this doesn't happen again, as to my knowledge, I can't find it anywhere in there. Perhaps add it to the list of 4 rules?

While I appreciate you linking me to that issue, you (as a project) can't expect a new potential contributor to go looking through _every issue ever filed_ just to check to make sure that all the rules are being followed.

If it is in the contributing guidelines, I apologise in advance. perhaps a quick summary would help?

**Comment by alex-nitrokey** [comment]
This is a fork of twofactorauth.org for being able to keep easily track of the changes there, we won't add sites they refuse.

The criteria is explained [here](https://github.com/Nitrokey/dongleauth/blob/device_authenticators/CONTRIBUTING.md#site-criteria) I admit that it could be more detailed, but again, this comes directly from twofactorauth.org It seems to work for them (they have much more issues/PR), so I guess most people go with it.

I mean both sites are basically about *services* not about *software* supporting 2fa. I think that is basically the reason why it is excluded. I could imagine to have a section "Software" too, but this would be a request on twofactorauth.org first. And I think they already discussed this kind of stuff iirc.

**Comment by rugk** [comment]
Every _software_ that you can self-host is a _service_ that supports 2FA then. Each of the single instance. And you have a common name for it (Nextcloud), so there is nothing wrong with that.

I mean it's not that you list OTP clients or so (while you have one such category), basically Nextcloud is also just a (web) service, just that you self-host it.

**Comment by rugk** [comment]
BTW, you (in contrast to upstream) **already support Mastodon**, which is also self-hosted software, so IMHO you can make it [better than upstream](https://github.com/2factorauth/twofactorauth/pull/3550) and not discriminate against self-hosted software.

**Comment by sbrl** [comment]
Well said, @rugk.

Is there an alternative database then, @alex-nitrokey? This information is important for me, so if there was somewhere else I could get it from, that'd be great :D

**Comment by rugk** [comment]
Can't we just manage this one here as a better alternative (database), i.e. a fork of twofactorauth? Apart from not that secure 2FA methods like mail or SMS or so it does support the big two (TOTP and UTF/FIDO/WebAuthn), so I now consider this here to be the better alternative/site.

**Comment by jans23** [comment]
We will add Nextcloud to the page.

**Comment by rugk** [comment]
I guess you'll just have to merge my PR. :smile:

**Comment by sbrl** [comment]
Awesome, thanks :D
