### ISSUE TITLE
Vultr support yubico key now

### ISSUE THREAD

**Issue by tasi788** [Nitrokey/dongleauth#139]
as title, i've tested and it works.
![img](http://file.sudo.host/2P2u2w0h2w2A/Image%2525202018-08-15%252520at%25252011.54.30%252520AM.png)

**Comment by alex-nitrokey** [comment]
Dongleauth.info does list technologies services support. As long as they do not support u2f in general (which I don't know) it does not make sense to change anything. Or what is your proposal?
