### ISSUE TITLE
Salesforce

### ISSUE THREAD

**Issue by dauthsubr** [Nitrokey/dongleauth#140]
Salesforce.com supports tokens and has invested in Yubico:
https://www.yubico.com/why-yubico/for-business/cloud/salesforce/
https://www.yubico.com/press-releases/30m-invested-yubico/

**Comment by alex-nitrokey** [comment]
Please have a look at the [definition note](https://github.com/Nitrokey/dongleauth/blob/device_authenticators/CONTRIBUTING.md#a-note-on-definitions).
Dongleauth lists services that support OTP and U2F(webauthn) only.

**Comment by dauthsubr** [comment]
Perhaps I'm not following, it looks like it does support U2F but also supports a few other types such as SMS, email and a dedicated app

https://help.salesforce.com/articleView?id=activating_computer.htm&type=5

If your average visitor to the site is supposed to figure out the intricacies of a paragraph in a text file on Github before making a suggestion, then I think if you are taking that same attitude to user adoption of the Nitrokey you're not exactly on to a winning formula. 

Why would documenting any site that supports a dongle like the domain name "dongleauth" suggests be a problem? It will be much better than looking at a site that seems like an abandoned incomplete project.

**Comment by alex-nitrokey** [comment]
Maybe *I* got you wrong. I didn't know what you are actually proposing.

From your first message, I only knew that salesforce supports yubico. A lot of services do, but that does not always qualify for a compatibility for u2f, which is used by [a lot dongles](https://www.dongleauth.info/dongles/). As you can see, dongleauth does have two columns: otp and u2f. I didn't know how your information should have fit in.

Thanks for the link to salesforce documentation. That makes the situation much more clearer. Would you mind to create a PR?
