### ISSUE TITLE
Is the site out of date?

### ISSUE THREAD

**Issue by brandon-arnold** [Nitrokey/dongleauth#142]
I came here because the site has no check under LastPass. After forking and going to `_data/identity.yml` however I see it has `Yes` for everything. What's going on?

**Comment by alex-nitrokey** [comment]
I see a check for LastPass regarding OTP. Do you may confuse twofactorauth.org and dongleauth.info? As OTP is not hardware-based auth for the people of twofactorauth.org, LastPass will identified as "hardware: No" there.

**Comment by brandon-arnold** [comment]
@alex-nitrokey I'm sorry, I see how my statement was not specific enough. Lastpass *does* support U2F with YubiKey, in the browser as well as over NFC on Android phone, for a year now.

Furthermore, in `_data/identity.yml` it says `hardware: Yes`. Which is valid. My point is that the website does not have a check under that column. AM I still missing something?

**Comment by alex-nitrokey** [comment]
Do you have any documentation which shows this feature (U2F support) for LastPass? Because I couldn't find one.

**Comment by brandon-arnold** [comment]
I lied about U2F @alex-nitrokey, it's OTP (see [here](https://lastpass.com/yubico/), [here](https://support.yubico.com/support/solutions/articles/15000006425-using-your-yubikey-with-lastpass), and [here](https://lastpass.com/support.php?cmd=showfaq&id=8126)). Still, OTP seems to also fit the bill, right?

**Comment by alex-nitrokey** [comment]
Sure, but it is already noted on the side, isn't it?
![screenshot_2018-10-01 usb dongle authentication](https://user-images.githubusercontent.com/36155797/46274923-5a26fb00-c55b-11e8-8f68-3b8e9a201ecb.png)

**Comment by brandon-arnold** [comment]
@alex-nitrokey Good point. I was mixing that column up with the OTP (as you stated in your very first response, mixing up twofactorauth with dongleinfo). So sorry for the waste of time :(

**Comment by alex-nitrokey** [comment]
no worries, thanks anyway
