### ISSUE TITLE
EVE online supports TOTP

### ISSUE THREAD

**Issue by AxMi-24** [Nitrokey/dongleauth#166]
EVE online supports TOTP for authentication both to the account management and for the game client.

**Comment by alex-nitrokey** [comment]
Could you provide a PR or at least give me basic information like a documentation reference?

**Comment by AxMi-24** [comment]
Hi, sorry didn't realise that was needed.
Here is the support page talking about it:
https://support.eveonline.com/hc/en-us/articles/203465601-Authenticator

Hope that helps

**Comment by alex-nitrokey** [comment]
thanks.
