### ISSUE TITLE
Dongleauth.org results in warning by Chrome that an attacker might be trying to steal your information

### ISSUE THREAD

**Issue by mcinun** [Nitrokey/dongleauth#169]
I started at https://cloud.google.com/titan-security-key/
then went to http://www.dongleauth.info and chose banking, taking me to 
http://www.dongleauth.info/#banking
i clicked on one of the "tell them to support USB dongle auth on twitter" and it posted this (first screenshot)
![screenshot 2018-11-27 at 4 09 52 pm](https://user-images.githubusercontent.com/45406777/49116686-00ddfe00-f264-11e8-9df6-754923fabc5b.png)

that if another twitter user clicks on results in this (second screenshot).
![screenshot 2018-11-27 at 4 10 23 pm](https://user-images.githubusercontent.com/45406777/49116701-0c312980-f264-11e8-88ef-0074948ca9ee.png)

**Comment by alex-nitrokey** [comment]
Thanks for letting us know! Honestly, I don't see what's going wrong here, but I could reproduce and I am on it...

**Comment by alex-nitrokey** [comment]
closed via e45ef34
