### ISSUE TITLE
Add Solo keys to list of dongles

### ISSUE THREAD

**Issue by tydog98** [Nitrokey/dongleauth#178]
[Solo key is a new open source security key](https://solokeys.com/)

**Comment by beerisgood** [comment]
Their website isn't privacy friendly: https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fsolokeys.com

**Comment by alex-nitrokey** [comment]
Would you mind creating a PR?

**Comment by NicolaiSoeborg** [comment]
This issue can be closed (fix: https://github.com/Nitrokey/dongleauth/pull/183)
