### ISSUE TITLE
Data updates

### ISSUE THREAD

**Issue by xoorath** [Nitrokey/dongleauth#181]
Hey, here are the accounts I have setup to use 2FA that are currently claiming unsupported on the website.

~Autodesk supports TOTP~ (solved)
Epic Games supports TOTP
Etsy supports TOTP
Itch.io supports TOTP

**Comment by schmidtch89** [comment]
Netcup also supports TOTP for their Customer Control Panel: https://www.netcup-wiki.de/wiki/Stammdaten_CCP#Mit_Zwei-Faktor-Authentifizierung_am_CCP_anmelden

**Comment by alex-nitrokey** [comment]
autodesk solved
