### ISSUE TITLE
DigitalOcean supports OTP

### ISSUE THREAD

**Issue by jdgregson** [Nitrokey/dongleauth#184]
[This page](https://www.dongleauth.info/#cloud) indicates that DigitalOcean does not support any 2FA methods, but it does support OTP.

**Comment by alex-nitrokey** [comment]
Please provide a PR and may paste a link here which confirms your statement.

**Comment by vt0r** [comment]
https://www.digitalocean.com/docs/accounts/security/2fa/#using-an-app-preferred
