### ISSUE TITLE
HDFC bank support for FIDO2

### ISSUE THREAD

**Issue by jigarshah** [Nitrokey/dongleauth#187]
https://netbanking.hdfcbank.com/netbanking/

**Comment by eternaltyro** [comment]
Wut? Can you cite the source for this? As far as I can tell, it doesn't support any non-SMS based 2FA.

**Comment by egurn** [comment]
@jigarshah Could you please provide a source? (e.g. a link to their docs or some screenshots)

**Comment by jigarshah** [comment]
@eternaltyro yes. It only supports SMS. Hence added link. I thought may be someone can pursue them for Fido based login :)

....List of sites with two factor auth support which includes **SMS**, email, phone calls, hardware, and software....

**The goal of this project is to build a website ([2fa.directory](https://2fa.directory/)) with a list of popular sites that support two factor** authentication, as well as the methods that they provide.

Our hope is to aid consumers who are deciding between alternative services based on the security they offer for their customers. This project also serves as an indicator of general security efforts used on a site.

**Comment by eternaltyro** [comment]
This particular repository only tracks sites that offer FIDO / U2F based authentication. The text you quote (and the website link) is from the parent repository.

The site for this fork is here: https://www.dongleauth.com/

**Comment by 103058167** [comment]
@jigarshah I was unable to find any recent documentation highlighting the use of OTP login or new implementation of U2F login authentication. As mentioned by eternaltyro this repository aims to focus on organization who support U2F 

https://www.hdfcbank.com/personal/useful-links/security/security-measures

However I did find that HDFC Bank do support OTP for financial transactions 
https://www.hdfcbank.com/personal/useful-links/security/security-measures/additional-security

Please do link documentation if you find any that support this case.
