### ISSUE TITLE
WhatsApp: add twitter page & tweet button

### ISSUE THREAD

**Issue by idavydov** [Nitrokey/dongleauth#192]
It would be great to add twitter profile link for WhatsApp.

* [whatsapp@twitter](https://twitter.com/whatsapp)

**Comment by beerisgood** [comment]
No. Don't use that privacy nightmare crap. Better use Mastodon or other decentralized services

**Comment by beerisgood** [comment]
Sadly nobody don't care about
But got lucky with your Twitter & WhatsApp. I guess it provide more money in the end
