### ISSUE TITLE
Add American Airlines Credit Untion (AACU)

### ISSUE THREAD

**Issue by TerminallyTransient** [Nitrokey/dongleauth#195]
AA Credit Union only allows the use of SMS verification at this time.  AACU (bank) is seperate from American Airlines (The Airline)

Website: https://www.aacreditunion.org/
Twitter: @AACreditUnion
Facebook: https://www.facebook.com/AACreditUnion/

**Comment by 103058167** [comment]
@TerminallyTransient dongleauth.com would prefer when adding new organizations that have not been previously listed/forked from upstream to support either One Time Passwords (OTP) or Universal 2nd Factor (U2F). Therefore the PR has been rejected
