### ISSUE TITLE
Dwolla 2FA for payments

### ISSUE THREAD

**Issue by pbnjay** [Nitrokey/dongleauth#20]
I love dwolla for ACH payments, they recently added 2FA. 
http://blog.dwolla.com/introducing-two-factor-authentication-dwolla/

I think they would be up for USB dongles also (I'd love to see it)

I'm on mobile right now, but I can do a PR later if necessary.

**Comment by jans23** [comment]
Dwolla supports Google Authenticator which implicates that they support standard-compliant One Time Passwords. Please submit a pull request. Thanks.
