### ISSUE TITLE
Update Microsoft Services with support for FIDO2

### ISSUE THREAD

**Issue by prajaybasu** [Nitrokey/dongleauth#207]
All Microsoft services support FIDO CTAP2 based logins with Microsoft accounts on Edge (EdgeHTML), Edge (Chromium) and Firefox starting with Windows 10 version 1809.  
https://www.microsoft.com/en-us/microsoft-365/blog/2018/11/20/sign-in-to-your-microsoft-account-without-a-password-using-windows-hello-or-a-security-key/

All Microsoft services also support FIDO2 CTAP and physical OATH tokens for Azure AD accounts starting with version 1809. Additionally, Azure AD joined accounts can use FIDO2 keys for Windows login too starting with version 1903.

https://techcommunity.microsoft.com/t5/Azure-Active-Directory-Identity/Announcing-the-public-preview-of-Azure-AD-support-for-FIDO2/ba-p/746362

Microsoft has also published a list of [requirements](https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/microsoft-compatible-security-key) for a security key to be Microsoft compatible.  

FIDO U2F is not supported for any service, and likely will not be supported due to the security requirements.

This affects all Microsoft services including Office 365 since all Microsoft services use SSO via MS Account or AAD.  

Right now, Office 365, Microsoft Azure, HealthVault and Microsoft To-Do all support FIDO2 based authentication on the web browsers however dongleauth.org is not updated. HealthVault is being retired in November 2019 though.  

See [this](https://github.com/2factorauth/twofactorauth/issues/3581#issuecomment-512831774) comment on twofactorauth repo.

**Comment by 103058167** [comment]
Changes to Microsoft Azure, HealthVault and Microsoft ToDo has been made in PR #323
