### ISSUE TITLE
Steam 2nd factor

### ISSUE THREAD

**Issue by cruzzer** [Nitrokey/dongleauth#23]
Hello Nitrokey

Steam provides two factor per [app ](https://support.steampowered.com/kb_article.php?ref=1266-OAFV-8478#steamguard)and sms OTP.

Regards

**Comment by jans23** [comment]
dongleauth's focus is on 2nd factor authentication with USB dongles. Technically this would be One Time Passwords (RFC 4226, RFC 6238) or FIDO U2F. It looks like Steam doesn't support any of those.
