### ISSUE TITLE
deploy the website

### ISSUE THREAD

**Issue by srouquette** [Nitrokey/dongleauth#232]
the website is out of date, and it doesn't seem to be deployed automatically.
"Firefox" accounts supports OTP now and is updated on the visible branch (because it's an update from upstream) but the website doesn't have this update.
This update is in the branch since September.

**Comment by alex-nitrokey** [comment]
Can you provide links to your statements because I think here are some misunderstandings but I can not clear that without knowing what exactly you are referring to. The website is deployed automatically and up-to-date.

**Comment by srouquette** [comment]
This file: https://github.com/Nitrokey/dongleauth/blob/device_authenticators/_data/other.yml#L244

But on dongleauth.info, it still shows as "unsupported" when you search "firefox".

**Comment by alex-nitrokey** [comment]
That is right. It is not supported for hardware tokens. Or if it is, then there need to be a `hardware: Yes` tag. Please see [our goal](https://github.com/Nitrokey/dongleauth#the-goal).
