### ISSUE TITLE
websites that allow hardware token bypass. (SMS backup)

### ISSUE THREAD

**Issue by zee0** [Nitrokey/dongleauth#237]
i'm looking specifically at the entry for vanguard, which has the **WebAuthn, FIDO2, U2F** column checked. it has an exception icon stating the following, but i'm not sure it is enough:

> Hardware based 2FA requires SMS / Phone call 2FA as a backup. Hardware 2FA is only supported on Chrome browsers and works with the following hardware keys: Yubikey 4 Series, YubiKey 5 Series, Yubikey Security Key Series.

this is misleading as vanguard's policy requiring SMS as a 2FA backup means that **the hardware token is always able to be bypassed.** as such, i don't think they should be getting credit for having hardware tokens.

if it were up to me there would be a big red x in that column stating that their implementation was misconfigured and potentially dangerous.

**Comment by 103058167** [comment]
@zee0 Exceptions have been removed for the Vanguard entry. Looking at their documentation linked below on U2F and FIDO, I can't find any information in the limitations suggested above. It seems that they have updated the policy/systems to accommodate for standard use of security keys.

Link: https://investor.vanguard.com/trust-security/security-center#modal-keys

If you happen to find contradicting policy/statements from Vanguard, please do link and dongleauth.com can reopen the issue.
