### ISSUE TITLE
No FIDO2/WebAuth on Synology DSM

### ISSUE THREAD

**Issue by OderDochNicht** [Nitrokey/dongleauth#244]
Clicking on the docs icon a synology documentation page opens showing "3. Configure DSM users' permission settings"
A little bit further down there is a description how to set up "6. Protect your account with 2-step verification" using TOTP.

I - and synology's search - cannot find anything about FIDO2 or webauth.

But dongleauth lists Synology as green.

**Comment by alex-nitrokey** [comment]
It is listed green for supporting OTP which is the case if I understand you correctly.
