### ISSUE TITLE
Distinguish between U2F and FIDO2

### ISSUE THREAD

**Issue by tim-hellhake** [Nitrokey/dongleauth#245]
As a user, I would like to see which sites are using the hardware token as second factor (U2F) and which sites use the hardware token for passwordless login (FIDO2).

**Comment by bgmnt** [comment]
this is kind of important, since you have to explore every service individually just by chance. to prevent false information (no fido2, red cross or no check tick) a question mark for "features not know so far" would be the right way in usability.

**Comment by alex-nitrokey** [comment]
Fixed via d840b47
We decided to add an icon at first. So far there just are nearly zero services providing it. Once there is more adaption, we can easily add a column.

**Comment by szepeviktor** [comment]
> So far there just are nearly zero services providing it.

We are redesigning our audiobook service. All internal/affiliate systems will be FIDO2/WebAuthn *only*.
