### ISSUE TITLE
Hype is in the list but supports OTP!

### ISSUE THREAD

**Issue by Genio2003** [Nitrokey/dongleauth#248]
Hype is in the list but supports OTP!
As described in this Blog Post:
https://support.hype.it/hc/it/articles/360003627713-Il-tuo-primo-accesso-in-app

**Comment by alex-nitrokey** [comment]
It supports one-time password in terms of SMS, but not as in [RFC 6238](https://en.wikipedia.org/wiki/Time-based_One-time_Password_algorithm). Please see https://github.com/Nitrokey/dongleauth#the-goal
