### ISSUE TITLE
Add hosting: Alfahosting

### ISSUE THREAD

**Issue by Benqer0** [Nitrokey/dongleauth#251]
https://alfahosting.de/

**Comment by 103058167** [comment]
@Benqer0 I was only able to find OTP for account authentication, however there was no mention of U2F or the use of security keys to allow for logins. 

https://alfahosting.de/antworten-auf-ihre-fragen/?cid=109&id=451#a451.
https://alfahosting.de/antworten-auf-ihre-fragen/?cid=107&id=490#a490

Please do link the sites if you happen to find different documentation that supports the latter. 

dongleauth.com aims to focus on organization who support U2F for the user base.
