### ISSUE TITLE
Dashlane now supports U2F

### ISSUE THREAD

**Issue by ilya40umov** [Nitrokey/dongleauth#26]
Here is the link to their site: https://www.dashlane.com/en/fido-u2f

I've tested Dashlane with Yubikey Neo/Nano/Security Key. All worked just fine. (Registering keys requires  premium account though).

Even thought about updating identity.yml myself, but not sure regarding what field corresponds to U2F.

**Comment by jans23** [comment]
The page has been updated accordingly. Thanks.
