### ISSUE TITLE
Webseiten Aktualisierung

### ISSUE THREAD

**Issue by Memurame** [Nitrokey/dongleauth#261]
Die dongleauth Webseite und das Repo hier sind nicht auf dem gleichen Stand. Ich wollte die Info über Digitec aktualisieren, jedoch ist dioes bereits im Repo angepasst aber nicht auf der Seite ersichtlich. Wie wird die Seite aktualisiert und in welchen Abständen?

**Comment by alex-nitrokey** [comment]
Die Anzeige ist korrekt. Bitte beachte [README.md](https://github.com/Nitrokey/dongleauth#the-goal) und [CONTRIBUTING.md](https://github.com/Nitrokey/dongleauth/blob/device_authenticators/CONTRIBUTING.md#adding-a-site-that-supports-tfa).
