### ISSUE TITLE
Add: NordVPN Teams

### ISSUE THREAD

**Issue by acordiandude** [Nitrokey/dongleauth#264]
Add NordVPN Teams
https://nordvpnteams.com/
2FA comming soon

**Comment by alex-nitrokey** [comment]
will be added as soon as twofactorauth is merged again, thanks for the heads up though

**Comment by acordiandude** [comment]
2FA is now live on their website

**Comment by acordiandude** [comment]
> will be added as soon as twofactorauth is merged again, thanks for the heads up though

2FA is now live on their website

**Comment by 103058167** [comment]
Unable to find documentation support the use of U2F in NordLayer (was NordTeams). Only the support of OTP. 
dongleauth.com is to highlight organizations who support Universal 2nd Factor (U2F). 

Please list document suggesting security key implementation, if there is which I have missed. And we can reopen ticket.

https://help.nordlayer.com/docs/mfa-sso
![image](https://user-images.githubusercontent.com/91036886/213144409-45c9ffd5-f688-4cac-a171-8cccb1faa32b.png)
