### ISSUE TITLE
kucoin google 2fa not working what should i do?

### ISSUE THREAD

**Issue by altblockchain** [Nitrokey/dongleauth#267]
### Importance of kucoin Google 2FA
Whenever you create an account you are pushed to have the password for your account but sometimes it's not enough to secure your account from potential theft according to the past graph. So its always suggested for the users to bind their account with the [google-authenticator](www.altblockchain.info/services/kucoin_exchange_help) as it changes after every 30secs by google and it is something that can only be used once. Google authenticator is considered to be one of the safest and secure ways to secure the account from any kind of potential theft. So don’t miss Google 2FA.
We all know Kucoin Exchange 2FA Google authentication very important for all of us. So, in this case, may I visit [Kucoin Issues Help](www.altblockchain.info/services/kucoin_exchange_help)?

**Comment by alex-nitrokey** [comment]
I do not understand what this issue is about...
