### ISSUE TITLE
broken link to Mastodon instructions

### ISSUE THREAD

**Issue by jans23** [Nitrokey/dongleauth#268]
This link is broken https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/2FA.md

**Comment by egurn** [comment]
I replaced it with this one:
https://docs.framasoft.org/en/mastodon/User-guide.html#two-factor-authentication

See [here](https://github.com/Nitrokey/dongleauth/commit/5d1fc4bfb65b64515227454d5acd527331191445).
