### ISSUE TITLE
Please add "Thetis FIDO2 Security Key" USB device

### ISSUE THREAD

**Issue by KNTRO** [Nitrokey/dongleauth#271]
Hello,

Please add [the **Thetis FIDO2 Security Key** USB device](https://thetis.io/collections/fido2/products/thetis-fido2-security-key) to [the _Two Factor Auth (2FA) Dongles_ webpage](https://www.dongleauth.info/dongles/).

![image](https://user-images.githubusercontent.com/2568821/91772626-a05bbd80-ebbb-11ea-9d68-e14fdd36160f.png)

`otp: Yes`
`u2f: Yes`
`hardware: Yes`

**Comment by 103058167** [comment]
Submitted commit under PR #323, with suggested configuration. However wasn't able to find any documentation mentioning the support of OTP.

**Comment by KNTRO** [comment]
Hello,

Happy New Year 202**3**! 😅

This USB security key is hash-based message authentication code one time password actually ("HMAC OTP", or "HOTP").

**Comment by 103058167** [comment]
Can you please provide a link to the documentation or evidence supporting your statement?

**Comment by KNTRO** [comment]
@103058167 Yes. Just click on the first link on this issue. You will go to the product page where you can find this description below:
![image](https://user-images.githubusercontent.com/2568821/212874614-dff39e21-0d65-4057-8836-7d5dd633e305.png)

**Comment by 103058167** [comment]
Change has been updated, now live on website
