### ISSUE TITLE
Amazon Web Services: add single MFA device restriction

### ISSUE THREAD

**Issue by cuu508** [Nitrokey/dongleauth#273]
Amazon Web Services apparently support only [one MFA device per account](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_enable_u2f.html#replace-u2f-mfa):

> You can have only one MFA device (virtual, U2F security key, or hardware) assigned to a user at a time. If the user loses a U2F key or needs to replace it for any reason, you must first deactivate the old U2F key. Then you can add a new MFA device for the user. 

This is fine for TOTP but an important restriction for security keys: you cannot have one main key and a second backup key.
It would be good to mention this restriction.

**Comment by 103058167** [comment]
This has been change as mentioned in the link below
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_enable_fido.html#replace-u2f-mfa
> You can have up to eight MFA devices of any combination of the[ currently supported MFA types](https://aws.amazon.com/iam/features/mfa/) assigned to a use at a time with your AWS account root user and IAM users.

**Comment by eternaltyro** [comment]
For the record, this is no longer the case. AWS supports a combination of up to 8-methods per user including WebAuthn/U2F keys.
