### ISSUE TITLE
Wealthfront supports TOTP

### ISSUE THREAD

**Issue by toastal** [Nitrokey/dongleauth#275]
Wealthfront is currently on the list as red

https://support.wealthfront.com/hc/en-us/articles/211004563-How-do-I-enable-two-factor-verification-for-my-account-

But they support TOTP (and SMS, but not FIDO2, U2F)

**Comment by toastal** [comment]
I checked the code

https://github.com/Nitrokey/dongleauth/blob/device_authenticators/_data/investing.yml#L194-L200

It's in the main branch, but I guess the site's not updated yet

**Comment by jans23** [comment]
That should be checked.

**Comment by 103058167** [comment]
Changes have been made in pull request #322, linked below
https://github.com/Nitrokey/dongleauth/pull/322
