### ISSUE TITLE
Sophos supports Authenticator apps and SMS

### ISSUE THREAD

**Issue by chetwisniewski** [Nitrokey/dongleauth#283]
Under the security category, Sophos Central supports both Authenticator (TOTP) and SMS, but not U2F.

https://central.sophos.com

https://support.sophos.com/support/s/article/KB-000037078?language=en_US

**Comment by egurn** [comment]
I updated the info. (See [here](https://github.com/Nitrokey/dongleauth/commit/61adf0b8322fc1a30e85a2e5380688fbb9fa50e6)

Thank your for your contribution!
