### ISSUE TITLE
Zoho.com supports TOTP and U2F

### ISSUE THREAD

**Issue by ImRobbieRobski** [Nitrokey/dongleauth#285]
I believe this will apply to any zoho app and not just mail. But as a consumer I only use mail, so I can't verify other apps, but it's reasonable to assume they'd support this across the board.
name: zoho
url: https://www.zoho.com
tfa: Yes
hardware: Yes
otp: Yes
u2f: Yes
doc: https://help.zoho.com/portal/en/kb/accounts/multi-factor-authentication/articles/mfa-yubikey#Using_YubiKey_with_Zoho_Accounts
https://help.zoho.com/portal/en/kb/accounts/multi-factor-authentication/articles/mfa-mobile-based-otp
https://www.zoho.com/mail/help/adminconsole/two-factor-authentication.html

**Comment by eternaltyro** [comment]
Zoho does support both TOTP and U2F keys . Multiple keys are supported as well. When I tried to login, only TOTP was presented though and I had to click on "Trouble Logging In " and select my Yubikey to login. 

Zoho - despite what it indicates - supports generic U2F keys other than Yubikey. My Solokey worked just fine.

**Comment by jans23** [comment]
Update incorporated.
