### ISSUE TITLE
Google services are Chrome-only, do not support U2F with Firefox

### ISSUE THREAD

**Issue by kno10** [Nitrokey/dongleauth#29]
While other services work with the Firefox add-on, Google does not.
IMHO this should be mentioned in a footnote, that currently Google U2F is Chrome-only.

**Comment by jans23** [comment]
I think the Firefox U2F addon did progress well. Do you know if this is still valid?

**Comment by kno10** [comment]
The Firefox add-on **works on other sites, except Google**. On Google, U2F is still a Chrome-only option. It will automatically fall back to other authentication options (e.g. SMS) with Firefox, unfortunately.

**Comment by jans23** [comment]
Thanks. I added a note at the listed Google services.
