### ISSUE TITLE
eBay supports WebAuthn

### ISSUE THREAD

**Issue by cobaltjacket** [Nitrokey/dongleauth#293]
I'm not really sure how the template works for this one as it's an unusual case, but eBay supports WebAuthn. I have tested this on a Mac with TouchID and an iPhone with FaceID (both times in Safari). Their example is from an Android device using Chrome.

https://tech.ebayinc.com/product/ebay-makes-mobile-web-login-easier/

**Comment by RAYs3T** [comment]
Can confirm this works. Just set it up a few minutes ago.
![image](https://user-images.githubusercontent.com/16596807/150014456-6bf51340-21db-4adb-b0f9-61b547143707.png)

**Comment by ott** [comment]
@RAYs3T I cannot confirm that this works. How did you set this up? “Security key” is an option in the two-factor authentication settings.

**Comment by 103058167** [comment]
Able to setup authentication method in settings as website suggest 
![image](https://user-images.githubusercontent.com/91036886/212295643-6dc54ea3-a4e4-471c-9ad5-c35286e197af.png)

**Comment by ott** [comment]
@103058167 Which URL did you use to get to the page?

**Comment by 103058167** [comment]
Linked below.. But it has come to my attention that depending on what browser you are using you may not have the option.
You should be able to check if you browser is viable via this link https://caniuse.com/#feat=webauthn. 

I'm using Google Chrome version 109.0.5414.74

https://accounts.ebay.com/acctsec/security-center

**Comment by jans23** [comment]
Another factor may be the user's country because I use the same browser but don't have this option. To be investigated...

**Comment by ott** [comment]
@103058167 I tried the link in both Mozilla Firefox and Chromium but it did not work. In both cases the locale of the browser was English and most of the eBay user interface was in English, with only minor parts in German. I used an eBay account that was first registered in Germany and accessed the website from an IP address that is geolocated to Germany. Moreover, I already have SMS two-factor authentication enabled.

@jans23 You might be right. It seems however that a more systematic search for the exact conditions might be required. For example, at first I thought that this feature is only available to eBay accounts that were registered in the USA. However, the screenshot in this issue clearly shows a German user interface and the eBay account might be registered in a country where German is the primary language.

What can be concluded though is that the feature does not seem to be universally available.

**Comment by Chris2000SP** [comment]
I cannot confirm ebay dot de, maybe dot com. But paypal dot com has it because i have fido2 usb token registered there. But i can use only one token, not two for backup. I came to it because i read news on heise dot de about it. Then i tested it and did work.

**Comment by 103058167** [comment]
Submitted a PR to add u2f with exception of country

**Comment by 103058167** [comment]
Change has been merged, closing issue
