### ISSUE TITLE
Various sites that have added support, but are not listed

### ISSUE THREAD

**Issue by thedaveCA** [Nitrokey/dongleauth#299]
- Fastmail - Not limited to Firefox/Chrome, mobile Safari works, as does Fastmail's native iOS app.
- LeaseWeb - Does support TOTP.
- Linode - Does support TOTP.
- Kraken - Does support security key. There are several features which can have the same key or different keys, but, you cannot have multiple keys for one feature. Nonetheless, support now exists.
- OpenSRS - Does support TOTP.
- Square - Does support TOTP.
- Toodledo - Does support TOTP.
- Twitter - Now allows multiple security keys.
- Uber - Does support TOTP although they hide it a bit.
- VoIP.ms - Does support TOTP.

Sorry, but git and I do not get along, so I'm not filing a pull request.

**Comment by britiger** [comment]
The last closed issue and merged pull request was June 2020, so I this repo and the page seams to be dead.

**Comment by thedaveCA** [comment]
Sad but true.

**Comment by 103058167** [comment]
Changes have been merged and are now live on site.
