### ISSUE TITLE
Tesla doesn't support WebAuth

### ISSUE THREAD

**Issue by itz-Jana** [Nitrokey/dongleauth#313]
Tesla is listed as supporting WebAuth, but it doesn't.
The linked Docs page mentions Security Keys, but only related to TOTP: https://www.tesla.com/support/multi-factor-authentication

**Comment by 103058167** [comment]
Made a PR for change #323

**Comment by 103058167** [comment]
Change merged. Removed u2f for Tesla, as support for U2F was not found.
