### ISSUE TITLE
Update: Schwab supports OTP via Symantec VIP

### ISSUE THREAD

**Issue by Laikulo** [Nitrokey/dongleauth#316]
Charles Schwab now supports OTPs from Symantec's VIP.
It used to require a call in for provisioning, but now they have it as self supported. It supports multiple devices and is also supported on their employee savings systems (401k, etc) I'm personally using this with a YubiKey with a Symantec credential in one of its slots.

**Comment by 103058167** [comment]
Change has been made in pull request  #321 and is now live on website
