### ISSUE TITLE
Paypal.com has Fido implemented for 1 key

### ISSUE THREAD

**Issue by Chris2000SP** [Nitrokey/dongleauth#333]
If you want to add an information please provide at least the following information:
* https://www.paypal.com/myaccount/security/ (can't find article directly from paypal.com)
* Has that info from this article: https://www.heise.de/news/PayPal-Passkey-statt-Passwort-fuer-Apple-Nutzer-7320313.html

I have a USB fido2 only stick and register it successfully. But i have Two Sticks in use and a third new stick not in use, but i can use only my first stick because paypal.com did not allow a second key.

I don't know how to get info about what paypal.com uses, CTAP1 or CTAP2. It did not request me to type the pin though.

Using Linux, Firefox. But i have also Chromium installed.

**Comment by 103058167** [comment]
Created PR, awaiting merge

**Comment by 103058167** [comment]
Change updated on website

**Comment by Chris2000SP** [comment]
I reopen this for a sec. I discovered that "Passkeys" on Paypal now since a couple of Month only support Smartphone Passkeys like iOS or Google Android.

https://securepayments.paypal.com/de/cshelp/article/wie-logge-ich-mich-mit-einem-passkey-bei-paypal-ein-help997

They kicked out the Fido2 Hardware Tokens but the Other one didn't.
I can not Login with my Nitrokey 3 anymore.
