### ISSUE TITLE
Crowdsourced Dongle Comparison

### ISSUE THREAD

**Issue by stv0g** [Nitrokey/dongleauth#373]
Hi all,

I've started to create a crowdsourced dongle comparison Google sheet here:

https://docs.google.com/spreadsheets/d/1XlwmreiBkt82F4HG965Yp9ncULkgnFpNyfe7WAAtYPk/edit?usp=sharing

Maybe we want to include it into the page?

**Comment by jans23** [comment]
Thanks for the suggestion but I don't see that it fits here nicely.
