### ISSUE TITLE
Posteo.de missing

### ISSUE THREAD

**Issue by Diapolo** [Nitrokey/dongleauth#50]
AFAIK Posteo ist also able to use two-factor-auth:
https://posteo.de/en/help/what-is-two-factor-authentication-and-how-do-i-set-it-up

Would be nice to add it to the list?

**Comment by jans23** [comment]
Thanks for your note. Could you provide a pull request for this? That
would be great.

**Comment by rugk** [comment]
No Posteo does not support U2F. They only support "traditional" 2FA, so they are included at https://twofactorauth.org/.

**Comment by beerisgood** [comment]
Sadly rugk is right.
Posteo only provide normal 2FA, no U2F

**Comment by techge** [comment]
You're right, only TOTP. We'll include it. 
We need some updating in general and try to do asap!
