### ISSUE TITLE
[device] add u2fzero

### ISSUE THREAD

**Issue by shazz** [Nitrokey/dongleauth#51]
Student built and now sells on amazon a cheap damn good u2f key

https://www.u2fzero.com/

the story: https://conorpp.com/2016/09/23/designing-and-producing-2fa-tokens-to-sell-on-amazon/

**Comment by jans23** [comment]
Thanks. Could you provide a pull request, please?

**Comment by archi** [comment]
Updated Blog Link: https://conorpp.com/designing-and-producing-2fa-tokens-to-sell-on-amazon
Amazon: https://www.amazon.com/U2F-Zero/dp/B01L9DUPK6

But the product is not available anymore. So you should probably link to his github for those who are both paranoid enough ;) and/or interested in building their own key. That is, if DIY stuff should go onto the page.
