### ISSUE TITLE
Merge back with twofactorauth.org

### ISSUE THREAD

**Issue by jdeluyck** [Nitrokey/dongleauth#61]
Wouldn't it make a lot more sense to merge back with twofactorauth.org? One resource, instead of multiple lists all over the place?

**Comment by nickserv** [comment]
Agreed. Is this project providing information other than hardware token from twofactorauth.org?

**Comment by jans23** [comment]
dongleauth.info provides specific information which sites support one-time passwords and which supports U2F. twofactorauth.org doesn't and this is the very reason why we forked dongleauth.info in the first place. Before the fork I asked them if they would be intersted in showing such specific information but they were not.
