### ISSUE TITLE
OTP text on pages should link to OTP wikipedia page

### ISSUE THREAD

**Issue by eddiewebb** [Nitrokey/dongleauth#67]
Currently it points to page on the OATH group behind OTP standard, which is interesting, but confusing to users looking to understand what One-Time Passwords are.

Currently links to -> https://en.wikipedia.org/wiki/Initiative_For_Open_Authentication
Prosal links to -> https://en.wikipedia.org/wiki/One-time_password

I'll submit the most trivial PR for your consideration.

**Comment by jans23** [comment]
The definition of "OTP" in scope of dongleauth is RFC 4226 and 6238 only. All other OTP schemes is not the same what is meant here. That is why the link to Initiative for Open Authentication is correct. There you will find the two RFCs linked.
