### ISSUE TITLE
Serve dongleauth.info over HTTPS

### ISSUE THREAD

**Issue by doherty** [Nitrokey/dongleauth#80]
Please serve dongleauth.info over HTTPS. <https://letsencrypt.org> can provide a free certificates, and I'd be happy to help you figure out how to set that up if you want help.

**Comment by alex-nitrokey** [comment]
This got fixed by [GitHub](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/) (thankfully).

@jans23  Could you please enforce HTTPS in the settings like described in the link? I still don't have access to the settings parts of this repo.

**Comment by alex-nitrokey** [comment]
Oh, and please change the link in the repo description as well (I can't do this either :wink:).

**Comment by rugk** [comment]
:tada:
