### ISSUE TITLE
OVH has OTP support

### ISSUE THREAD

**Issue by karthanistyr** [Nitrokey/dongleauth#83]
The OVH entry states that there is 2FA support, but no tick for OTP, however OVH does support OTP as a 2FA means (i use it myself with nitrokey).

https://twitter.com/ovh/status/590450825425653760

**Comment by techge** [comment]
Closed by https://github.com/Nitrokey/dongleauth/commit/1cfd80ba6f7f8ca62636ab417fc0f9f12d5ba090
