### ISSUE TITLE
Twitter now supports One Time Passwords (OTP)

### ISSUE THREAD

**Issue by m-p-3** [Nitrokey/dongleauth#84]
It is now possible to register Twitter in apps such as Google Authenticator.

![twitter _ settings](https://cloud.githubusercontent.com/assets/3731432/25819150/06782dc8-33fb-11e7-9072-51cc43b8a00c.png)

**Comment by techge** [comment]
Do you know if it is requiered to leave phone number as stated dongleauth until now?
