### ISSUE TITLE
Vanguard now supports SMS 2FA

### ISSUE THREAD

**Issue by ghost** [Nitrokey/dongleauth#87]

**Comment by lyallcooper** [comment]
They also support U2F now

**Comment by techge** [comment]
Do you have any resource?

**Comment by Vednier** [comment]
It not official, but - https://www.turnon2fa.com/tutorials/how-to-turn-on-2fa-for-vanguard/

**Comment by alex-nitrokey** [comment]
Hey, thanks, but this isn't about U2F, is it? I meant this information.

The title's content (supporting SMS) is of no interest for this site anyway. I would have closed this if @lyallcooper hadn't told us about U2F :thinking:

**Comment by alex-nitrokey** [comment]
Mh, it looks for me, that it has to be hardware: No (seems to be wrong on twofactorauth as well). Only phone and text is supported, isn't it?

**Comment by lyallcooper** [comment]
They definitely do support U2F—I have it enabled on my account. You may have to be logged in to see the relevant documentation, but an excerpt from [the "Security Keys" enrollment page](https://personal.vanguard.com/us/U2FKeyEnrollment) is as follows:

> **Security key terms & conditions**
>
> These Terms and Conditions set forth what you can expect from your use of a Key to access your Vanguard accounts, as well as your and Vanguard's related rights and obligations. As used in these Terms and Conditions, "Key" means a security key that supports FIDO U2F specifications and appears on Vanguard's compatibility list, which currently includes the following keys:
> 
> - Yubikey FIDO U2F Security Key
> - Yubikey NEO
> - Yubikey 4 NANO
> - Yubikey 4
>
> This list may be modified from time to time (including to remove a security key previously listed as compatible and/or to add a new security key) in Vanguard's sole discretion. A security key that does not support FIDO U2F specifications and appear on the compatibility list may not be used to access your Vanguard accounts. Please note that, including a security key on the compatibility list does not constitute any representation or warranty that the security key will work as intended in every circumstance or in your particular IT environment, that the security key you purchase will not have defects, or that the security key will be more secure than a security key that does not appear on the list.

In addition, they support OTP over SMS.

**Comment by alex-nitrokey** [comment]
Okay, I will change the entry.
It's really a pity that they don't have instructions world readable :roll_eyes: 
Thanks for keeping us updated!
