### ISSUE TITLE
Zapier now has TOTP

### ISSUE THREAD

**Issue by lvh-zapier** [Nitrokey/dongleauth#89]
I would've created a pull request, but we've already fixed it upstream, so maybe you prefer to forward merge.

**Comment by jans23** [comment]
A pull request would be much aprreciated.

**Comment by lvh-zapier** [comment]
Is your intention to preserve the split with upstream? They've created quite a few changes, and to be honest, I can't really tell why this repo exists.

**Comment by jans23** [comment]
Yes, the split will remain as long as twofactorauth.org doesn't show
which service supports one-time passwords and FIDO U2F. You can't get
this information from twofactorauth.org currently.

>
