### ISSUE TITLE
Add Universal Authentication Framework (UAF) column

### ISSUE THREAD

**Issue by HLFH** [Nitrokey/dongleauth#9]
Hi,

I know that U2F is now supported by a bunch of projects: Dropbox, WordPress, OpenSSH, Linux PAM, GitHub, Google Accounts.

But I would like we add an Universal Authentication Framework (UAF) column because in 2016, UAF should be supported in some main websites. If we don't promote UAF, I'm not sure it will be widespread like U2F.

**Comment by jans23** [comment]
This page is dedicated for USB dongle support. AFAIK UAF is not designed to work with USB token so adding UAF would shift the focus. This may be reasonable if there would be some traction in the future but not yet.

**Comment by HLFH** [comment]
So @jans23 do you confirm that the [IDKey](http://www.idkey.com/) is _not_ a USB dongle that supports UAF and U2F? I'm sure that UAF is also designed to work with USB token. Or am I wrong? 

As you could see [in the UAF specs](https://fidoalliance.org/specs/fido-uaf-v1.0-ps-20141208/fido-uaf-authnr-cmds-v1.0-ps-20141208.pdf), FIDO Alliance give some examples of UAF Authenticators:

> A fingerprint sensor built into a mobile device
> PIN authenticator implemented inside a secure element
> A mobile phone acting as an authenticator to a different device
> **A USB token with built-in user presence verification**
> A voice or face verification technology built into a device

So, maybe you could reopen this issue.

**Comment by jans23** [comment]
Valid point. Do you volunteer to implement another column for UAF?

**Comment by HLFH** [comment]
@jans23 Yes, I'm volunteer. I'll make the PR on 10/8/2015 in two days if you're ok and if it's not too late :)

**Comment by HLFH** [comment]
For now, UAF is not really supported. At least, eBay is helping the [FIDO UAF standard](https://fidoalliance.org/ebay-joins-fido-alliance-and-announces-fido-certified-open-source-authentication-server-and-android-client/) but no general availability yet. The UAF products now exist but there are no real use cases for this moment.
