### ISSUE TITLE
ClouDNS (finally) supports OTP

### ISSUE THREAD

**Issue by ItTakesTwo** [Nitrokey/dongleauth#98]
ClouDNS.net implemented OTP some month ago. You might want to add it to your summary.

**Comment by jans23** [comment]
Thanks for the info. Could you provide a pull request, please?

**Comment by ItTakesTwo** [comment]
Of course: https://github.com/Nitrokey/dongleauth/pull/99

**Comment by techge** [comment]
Closed by https://github.com/Nitrokey/dongleauth/commit/bc3d1d20015912f2342d137454ab3b8773de7720
